services:
  - type: web
    name: php-mvc-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DSN
        value: pgsql:host=ep-weathered-paper-a1xrzgcn-pooler.eu-central-1.pg.koyeb.app;port=5432;dbname=odc_maxit
      - key: DB_USER
        value: tinkin
      - key: DB_PASSWORD
        value: ironci
      - key: BASE_URL
        value: https://php-mvc-app.onrender.com/
